{{ if .Values.blue.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "MyApp.fullname" . }}-blue
  labels:
    app.kubernetes.io/name: {{ include "MyApp.name" . }}
    helm.sh/chart: {{ include "MyApp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    DeploymentType: blue
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      AppVersion: {{ .Values.release.number}}
      app.kubernetes.io/name: {{ include "MyApp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "MyApp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        AppVersion: {{ .Values.release.number}}
        DeploymentType: blue
    spec:
      containers:
        - image: golang:stretch
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: prometheus-agent
          command: ["sh", "-c", "tail -f /dev/null", "go get github.com/prometheus/node_exporter", "cd ${GOPATH-$HOME/go}/src/github.com/prometheus/node_exporter", "make", "./node_exporter"]
          ports:
          - containerPort: 9100
            name: http
            protocol: TCP
        - name: {{ .Chart.Name }}-blue
          image: "{{ .Values.image.repository }}:{{ .Values.image.deploy_blue }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['sh', '-c', 'java -jar helloworld-springboot-0.0.1-SNAPSHOT.jar']
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}