apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repository
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
  volumeMode: Filesystem
